export const POKEMON_DATA = "POKEMON_DATA";
export const POKEMON_DATA_SUCCESS = "POKEMON_DATA_SUCCESS";
export const POKEMON_DATA_FAILURE = "POKEMON_DATA_FAILURE";
export const CLEAR_POKEMON_DATA = "CLEAR_POKEMON_DATA";

export const SAVE_USER_POKEMON_DATA = "SAVE_USER_POKEMON_DATA";